name: Version Check

on:
  pull_request:
    branches:
      - main

jobs:
  check-version:
    name: Check Version Bump
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Check if version was bumped
        run: |
          git fetch origin main:main
          MAIN_VERSION=$(git show main:package.json | grep '"version"' | head -1 | awk -F'"' '{print $4}')
          BRANCH_VERSION=$(cat package.json | grep '"version"' | head -1 | awk -F'"' '{print $4}')

          echo "Main branch version: $MAIN_VERSION"
          echo "PR branch version: $BRANCH_VERSION"

          if [ "$MAIN_VERSION" = "$BRANCH_VERSION" ]; then
            echo "⚠️  Warning: Version was not bumped in this PR"
            echo "Please run 'npm run release' to bump the version"
            exit 0
          else
            echo "✅ Version was bumped from $MAIN_VERSION to $BRANCH_VERSION"
          fi

  check-changelog:
    name: Check Changelog Update
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if CHANGELOG.md was updated
        run: |
          git fetch origin main:main
          if git diff --name-only main...HEAD | grep -q "CHANGELOG.md"; then
            echo "✅ CHANGELOG.md was updated"
          else
            echo "⚠️  Warning: CHANGELOG.md was not updated"
            echo "Consider updating the changelog with your changes"
          fi
